"use client";

import { useState, useEffect } from "react";
import { X, Sparkles, FileText, Loader2, Copy, Check } from "lucide-react";

interface SummaryModalProps {
  isOpen: boolean;
  onClose: () => void;
  file: {
    fileName: string;
    fileUrl: string;
    fileType: string;
  };
}

export default function SummaryModal({ isOpen, onClose, file }: SummaryModalProps) {
  const [summary, setSummary] = useState("");
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (isOpen && file) {
      generateSummary();
    }
  }, [isOpen, file]);

  const generateSummary = async () => {
    setLoading(true);
    setSummary(""); // Clear previous text

    try {
      const res = await fetch("/api/summarize", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        // 👇 UPDATE THIS SECTION
        body: JSON.stringify({
          fileName: file.fileName,
          fileType: file.fileType,
          fileUrl: file.fileUrl  // <--- CRITICAL: Send the actual link!
        }),
      });

      if (!res.ok) throw new Error("Failed to summarize");

      const data = await res.json();
      
      // ✅ FIX: Set text instantly to avoid double-text bug
      setSummary(data.summary);

    } catch (error) {
      setSummary("Error generating summary. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4 animate-in fade-in duration-200">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl overflow-hidden flex flex-col max-h-[85vh]">
        
        {/* Header */}
        <div className="bg-gradient-to-r from-purple-600 to-indigo-600 p-6 text-white flex justify-between items-start shrink-0">
          <div>
            <h2 className="text-xl font-bold flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-yellow-300" />
              AI Smart Summary
            </h2>
            <p className="text-purple-100 text-sm mt-1 flex items-center gap-2">
              <FileText className="w-4 h-4 opacity-70" />
              {file.fileName}
            </p>
          </div>
          <button onClick={onClose} className="text-white/80 hover:text-white transition hover:bg-white/10 p-2 rounded-full">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content Area */}
        <div className="p-6 overflow-y-auto flex-1 bg-gray-50/50">
          {loading && !summary ? (
            <div className="flex flex-col items-center justify-center h-48 space-y-4 text-gray-500">
              <Loader2 className="w-10 h-10 animate-spin text-purple-600" />
              <p className="text-sm font-medium animate-pulse">Analyzing document structure...</p>
            </div>
          ) : (
            <div className="prose prose-purple max-w-none">
              <div className="bg-white p-6 rounded-xl border border-gray-100 shadow-sm leading-relaxed text-gray-700 whitespace-pre-wrap">
                {summary}
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-gray-100 bg-white flex justify-between items-center shrink-0">
          <span className="text-xs text-gray-400 font-medium px-2">
            Generated by StudySync AI
          </span>
          <div className="flex gap-3">
            <button 
              onClick={handleCopy}
              className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium text-gray-600 hover:bg-gray-100 transition"
            >
              {copied ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
              {copied ? "Copied" : "Copy Text"}
            </button>
            <button 
              onClick={onClose}
              className="px-6 py-2 bg-black text-white rounded-lg text-sm font-medium hover:bg-gray-800 transition"
            >
              Done
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}